:PROPERTIES:
:ID:       fa113cbd-e8d3-42c5-97ae-eaa82a8257ec
:END:
#+TITLE: âš™ï¸ My Config
#+PROPERTY: header-args:emacs-lisp :tangle ~/.doom.d/config.el
#+STARTUP: fold

* Emacs Config
:PROPERTIES:
:ID:       ef84f824-9440-42b2-b69d-bc07aa10c5ef
:END:
** Headers
#+begin_src emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src

#+begin_src emacs-lisp :tangle "~/.doom.d/packages.el"
;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el
#+end_src


#+begin_src emacs-lisp :tangle "~/.doom.d/init.el"
;;; init.el -*- lexical-binding: t; -*-
#+end_src

** Packages
#+begin_src emacs-lisp :tangle "~/.doom.d/init.el"
(doom! :input
       ;;chinese
       ;;japanese
       ;;layout            ; auie,ctsrnm is the superior home row

       :completion
       company           ; the ultimate code completion backend
       ;;helm              ; the *other* search engine for love and life
       ;;ido               ; the other *other* search engine...
       ;;ivy               ; a search engine for love and life
       vertico           ; the search engine of the future

       :ui
       ;;deft              ; notational velocity for Emacs
       doom              ; what makes DOOM look the way it does
       doom-dashboard    ; a nifty splash screen for Emacs
       doom-quit         ; DOOM quit-message prompts when you quit Emacs
       ;;(emoji +unicode)  ; ðŸ™‚
       hl-todo           ; highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW
       ;;hydra
       ;;indent-guides     ; highlighted indent columns
       ;;ligatures         ; ligatures and symbols to make your code pretty again
       ;;minimap           ; show a map of the code on the side
       modeline          ; snazzy, Atom-inspired modeline, plus API
       ;;nav-flash         ; blink cursor line after big motions
       ;;neotree           ; a project drawer, like NERDTree for vim
       ophints           ; highlight the region an operation acts on
       (popup +defaults)   ; tame sudden yet inevitable temporary windows
       ;;tabs              ; a tab bar for Emacs
       ;;treemacs          ; a project drawer, like neotree but cooler
       ;;unicode           ; extended unicode support for various languages
       vc-gutter         ; vcs diff in the fringe
       vi-tilde-fringe   ; fringe tildes to mark beyond EOB
       ;;window-select     ; visually switch windows
       workspaces        ; tab emulation, persistence & separate workspaces
       ;;zen               ; distraction-free coding or writing

       :editor
       (evil +everywhere); come to the dark side, we have cookies
       file-templates    ; auto-snippets for empty files
       fold              ; (nigh) universal code folding
       ;;(format +onsave)  ; automated prettiness
       ;;god               ; run Emacs commands without modifier keys
       ;;lispy             ; vim for lisp, for people who don't like vim
       ;;multiple-cursors  ; editing in many places at once
       ;;objed             ; text object editing for the innocent
       ;;parinfer          ; turn lisp into python, sort of
       ;;rotate-text       ; cycle region at point between text candidates
       snippets          ; my elves. They type so I don't have to
       ;;word-wrap         ; soft wrapping with language-aware indent

       :emacs
       dired             ; making dired pretty [functional]
       electric          ; smarter, keyword-based electric-indent
       ;;ibuffer         ; interactive buffer management
       undo              ; persistent, smarter undo for your inevitable mistakes
       vc                ; version-control and Emacs, sitting in a tree

       :term
       eshell            ; the elisp shell that works everywhere
       ;;shell             ; simple shell REPL for Emacs
       ;;term              ; basic terminal emulator for Emacs
       ;;vterm             ; the best terminal emulation in Emacs

       :checkers
       syntax              ; tasing you for every semicolon you forget
       ;;(spell +flyspell) ; tasing you for misspelling mispelling
       ;;grammar           ; tasing grammar mistake every you make

       :tools
       ;;ansible
       ;;biblio            ; Writes a PhD for you (citation needed)
       ;;debugger          ; FIXME stepping through code, to help you add bugs
       ;;direnv
       ;;docker
       ;;editorconfig      ; let someone else argue about tabs vs spaces
       ;;ein               ; tame Jupyter notebooks with emacs
       (eval +overlay)     ; run code, run (also, repls)
       ;;gist              ; interacting with github gists
       lookup              ; navigate your code and its documentation
       lsp                 ; M-x vscode
       magit               ; a git porcelain for Emacs
       ;;make              ; run make tasks from Emacs
       ;;pass              ; password manager for nerds
       ;;pdf               ; pdf enhancements
       ;;prodigy           ; FIXME managing external services & code builders
       ;;rgb               ; creating color strings
       ;;taskrunner        ; taskrunner for all your projects
       ;;terraform         ; infrastructure as code
       ;;tmux              ; an API for interacting with tmux
       ;;upload            ; map local to remote projects via ssh/ftp

       :os
       (:if IS-MAC macos)  ; improve compatibility with macOS
       ;;tty               ; improve the terminal Emacs experience

       :lang
       ;;agda              ; types of types of types of types...
       ;;beancount         ; mind the GAAP
       ;;cc                ; C > C++ == 1
       ;;clojure           ; java with a lisp
       ;;common-lisp       ; if you've seen one lisp, you've seen them all
       ;;coq               ; proofs-as-programs
       ;;crystal           ; ruby at the speed of c
       ;;csharp            ; unity, .NET, and mono shenanigans
       ;;data              ; config/data formats
       ;;(dart +flutter)   ; paint ui and not much else
       ;;dhall
       ;;elixir            ; erlang done right
       ;;elm               ; care for a cup of TEA?
       emacs-lisp        ; drown in parentheses
       ;;erlang            ; an elegant language for a more civilized age
       ;;ess               ; emacs speaks statistics
       ;;factor
       ;;faust             ; dsp, but you get to keep your soul
       ;;fortran           ; in FORTRAN, GOD is REAL (unless declared INTEGER)
       ;;fsharp            ; ML stands for Microsoft's Language
       ;;fstar             ; (dependent) types and (monadic) effects and Z3
       ;;gdscript          ; the language you waited for
       ;;(go +lsp)         ; the hipster dialect
       ;;(haskell +lsp)    ; a language that's lazier than I am
       ;;hy                ; readability of scheme w/ speed of python
       ;;idris             ; a language you can depend on
       ;;json              ; At least it ain't XML
       ;;(java +meghanada) ; the poster child for carpal tunnel syndrome
       ;;javascript        ; all(hope(abandon(ye(who(enter(here))))))
       ;;julia             ; a better, faster MATLAB
       ;;kotlin            ; a better, slicker Java(Script)
       ;;latex             ; writing papers in Emacs has never been so fun
       ;;lean              ; for folks with too much to prove
       ;;ledger            ; be audit you can be
       ;;lua               ; one-based indices? one-based indices
       markdown          ; writing docs for people to ignore
       ;;nim               ; python + lisp at the speed of c
       ;;nix               ; I hereby declare "nix geht mehr!"
       ;;ocaml             ; an objective camel
       (org +pretty)       ; organize your plain life in plain text
       ;;php               ; perl's insecure younger brother
       ;;plantuml          ; diagrams for confusing people more
       ;;purescript        ; javascript, but functional
       ;;python            ; beautiful is better than ugly
       ;;qt                ; the 'cutest' gui framework ever
       ;;racket            ; a DSL for DSLs
       ;;raku              ; the artist formerly known as perl6
       ;;rest              ; Emacs as a REST client
       ;;rst               ; ReST in peace
       ;;(ruby +rails)     ; 1.step {|i| p "Ruby is #{i.even? ? 'love' : 'life'}"}
       (rust +lsp)         ; Fe2O3.unwrap().unwrap().unwrap().unwrap()
       ;;scala             ; java, but good
       ;;(scheme +guile)   ; a fully conniving family of lisps
       sh                ; she sells {ba,z,fi}sh shells on the C xor
       ;;sml
       ;;solidity          ; do you need a blockchain? No.
       ;;swift             ; who asked for emoji variables?
       ;;terra             ; Earth and Moon in alignment for performance.
       ;;web               ; the tubes
       ;;yaml              ; JSON, but readable
       ;;zig               ; C, but simpler

       :email
       ;;(mu4e +org +gmail)
       ;;notmuch
       ;;(wanderlust +gmail)

       :app
       ;;calendar
       ;;emms
       ;;everywhere        ; *leave* Emacs!? You must be joking
       ;;irc               ; how neckbeards socialize
       ;;(rss +org)        ; emacs as an RSS reader
       ;;twitter           ; twitter client https://twitter.com/vnought

       :config
       ;;literate
       (default +bindings +smartparens))
#+end_src

** General
#+begin_src emacs-lisp
(setq user-full-name "Urban Avsec"
      user-mail-address "urban.avsec@outlook.com")
#+end_src

Let's define some useful path varialbes for rest of configuration
#+begin_src emacs-lisp

(defvar urb/iCloud-path "~/Library/Mobile Documents/com~apple~CloudDocs/")

#+end_src

Just force the ~visual-line-mode~ on org. Based in [[https://github.com/hlissner/doom-emacs/issues/401][#401]] issue this should be added to =init.el= not config.
#+begin_src emacs-lisp :tangle ~/.doom.d/init.el
(setq evil-respect-visual-line-mode t)

#+end_src

Allow the use of native fullscreen window in Mac Emacs
#+begin_src emacs-lisp

(setq ns-use-native-fullscreen t)

#+end_src

** UI

Set ups the main theme of my emacs
#+begin_src emacs-lisp

(setq doom-theme 'doom-one)
(setq display-line-numbers-type t)

#+end_src

** Org
*** Auto Tangle My Main Configuration File

#+begin_src emacs-lisp

(defun urb/org-babel-tangle-my-configs ()
  (when (string-equal (buffer-file-name)
                      (expand-file-name "~/.dotenv/README.org"))
    (let ((org-confirm-babel-evaluate nil))
      (org-babel-tangle))))

(add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'urb/org-babel-tangle-my-configs)))

#+end_src

*** Citations in Org Files

Let's first define path to my =.bib= file and location where my pdfs and epubs will be stored
#+begin_src emacs-lisp
(defvar urb/reference-files (list (concat urb/iCloud-path "Library/References.bib")))
(defvar urb/reference-sources-dirs (list(concat urb/iCloud-path "Library/Files/")))

#+end_src

Let's install ~citar~ pacakge which will offer the UI interface for interacting with my bibtex file.
#+begin_src emacs-lisp :tangle ~/.doom.d/packages.el

(package! citar)

#+end_src

Configure ~citar~ pacakge to work in org mode
#+begin_src emacs-lisp
(use-package! citar
  :after org
  :no-require
  :config
  (setq org-cite-insert-processor 'citar
        org-cite-follow-processor 'citar
        org-cite-activate-processor 'citar)
  (setq citar-bibliography urb/reference-files
        citar-library-paths urb/reference-sources-dirs))
#+end_src

Finally setup Org Cite package to enable the citations
#+begin_src emacs-lisp

(use-package! oc
  :after citar
  :defer t
  :config
  (setq org-cite-global-bibliography '("~/Library/Mobile Documents/com~apple~CloudDocs/Library/References.bib")))

#+end_src

Use the ~org-cite~ processors
#+begin_src emacs-lisp

(use-package! oc-biblatex :after oc)

#+end_src

Let's also install ~org-ref~ to get bibtex support functions
#+begin_src emacs-lisp :tangle ~/.doom.d/packages.el

(package! org-ref)

#+end_src

And finally enable it
#+begin_src emacs-lisp

(use-package! org-ref
  :after org
  :config
  (setq bibtex-completion-bibliography urb/reference-files))

#+end_src

Provide some good keybinds
#+begin_src emacs-lisp

(map! (:map org-mode-map
       :leader
       :prefix ("R" . "cite & ref")
       "n" #'citar-open-notes
       "i" #'org-cite-insert
       "I" #'isbn-to-bibtex
       "R" #'citar-refres))

#+end_src

*** Let's Make It Pretty with Org-Download

Install ~org-download~
#+begin_src emacs-lisp :tangle ~/.doom.d/packages.el

(package! org-download)

#+end_src

And Enable it
#+begin_src emacs-lisp

(use-package! org-download)

#+end_src

The ~org-download~ should download all photos and other media in =/{org-dir}/Media= folder with some basic default settings.
#+begin_src emacs-lisp

(after! org
  :config
  (setq-default org-download-image-dir "Media"
        org-download-heading-lvl nil)
  (setq org-download-method 'directory
        org-download-timestamp "_%Y%m%d_%H%M%S"
        org-download-screenshot-method
          (cond (IS-MAC "screencapture -i %s"))
        org-download-annotate-function (lambda (_link) "#+ATTR_ORG: :width 300px\n")))

#+end_src

Finally provide keymaps to easily add pictures while I write my org files
#+begin_src emacs-lisp

(after! org
    (map! (:map org-mode-map
          :leader
          :prefix ("nr" . "org-roam")
          "S" #'org-download-screenshot)))

#+end_src

*** Org Roam
Installs ~org-roam~ from the gitrepo. To refresh the package ~doom sync~ must be called.

#+begin_src emacs-lisp :tangle "~/.doom.d/packages.el"

(package! org-roam
  :recipe (:host github :repo "org-roam/org-roam"
           :files (:defaults "extensions/*")))

#+end_src

Lodas ~org-roam~ package and provides basic configuration

#+begin_src emacs-lisp

(setq org-directory "~/Library/Mobile Documents/com~apple~CloudDocs/Cortex")
(use-package! org-roam
  :init
  (setq org-roam-v2-ack t)
  :config
  (setq org-roam-directory "~/Library/Mobile Documents/com~apple~CloudDocs/Cortex")
  (org-roam-setup))


#+end_src

Configures my org-roam dailies

#+begin_src emacs-lisp

(after! org-roam
  (setq org-roam-dailies-directory "Journal/"))

#+end_src

Provides the key bindings for org-roam in my system

#+begin_src emacs-lisp

(map! (:map org-mode-map
        :leader
        :prefix ("nr" . "org-roam")
        "f" #'org-roam-node-find
        "i" #'org-roam-node-insert
        "I" #'org-id-get-create
        "t" #'org-roam-dailies-goto-today
        "s" #'org-roam-db-sync
        "m" #'org-roam-buffer-toggle))

#+end_src

I use two core templates for new org-roam nodes.
+ /Note/ - Is the plain note template for general purpose note placed in the root of my cortex.
+ /Reference/ - Is a structured note template for notes which track my processed references and bibliography.

#+begin_src emacs-lisp

(after! org-roam
  (setq org-roam-capture-templates
        '(("n" "Note" plain "%?"
           :target (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+TITLE:${title}\n")
           :unnarrowed t)
          ("r" "Reference" plain "%?"
           :target (file+head "References/${citekey}.org"
                              "#+TITLE:${title}\n#+FILETAGS: Reference\n \n* Summary\n* Notes\n")))))

#+end_src



**** Org Roam Bibtex

Integrate ~org-roam~ with my citations using ~org-roam-bibtex~

Firstly install ~org-roam-bibtex~ from repo

#+begin_src emacs-lisp :tangle "~/.doom.d/packages.el"

(package! org-roam-bibtex
  :recipe (:host github :repo "org-roam/org-roam-bibtex"))

#+end_src

Then enable the package and integrate it with the ~citar~ citation procesor. For its config look at [[Citations in Org Files]] section.

#+begin_src emacs-lisp
(use-package! org-roam-bibtex
  :after org-roam
  :config
  (setq bibtex-completion-bibliography org-cite-global-bibliography
        citar-open-note-function 'orb-citar-edit-note
        citar-notes-paths (list org-roam-directory))
  (org-roam-bibtex-mode))

#+end_src

Adds the core keybindings for interraction with references from emacs

#+begin_src emacs-lisp
(map! (:map org-mode-map
       :leader
       :prefix ("R" . "cite & ref")
       "a" #'orb-note-actions))

#+end_src

**** Org Roam UI

Get the package
#+begin_src emacs-lisp :tangle ~/.doom.d/packages.el

(package! org-roam-ui
  :recipe (:host github :repo "org-roam/org-roam-ui"
           :files ("*.el" "out")))

#+end_src

Then enable the websocket package
#+begin_src emacs-lisp

(use-package! websocket :after org-roam)

#+end_src

Finally configure ~org-roam-ui~
#+begin_src emacs-lisp

(use-package! org-roam-ui
  :after org-roam
  :hook (after-init . org-roam-ui-mode)
  :config
  (setq org-roam-ui-sync-theme t
        org-roam-ui-follor t
        org-roam-ui-update-on-save t
        org-roam-ui-open-on-start t))


#+end_src
